backend/models/QueryRequest.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "query_request".
 *
 * @property string $id
 * @property string $ezf_id
 * @property string $target_id
 * @property string $data_id
 * @property string $ezf_field_id
 * @property string $new_val
 * @property string $old_val
 * @property string $note
 * @property integer $status
 * @property string $user_create
 * @property string $user_update
 * @property string $time_create
 * @property string $time_update
 * @property string $approved_by
 * @property string approved_note
 * @property string $userkey
 * @property string $userkey_status
 * @property string $new_changed
 * @property string $open_status
 * @property string $xsourcex
 */
class QueryRequest extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'query_request';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ezf_field_id'], 'required', 'message'=>'กรุณาเลือก Field'],
            [['ezf_id', 'target_id', 'data_id', 'ezf_field_id', 'status', 'user_create', 'user_update', 'approved_by'], 'integer'],
            [['ezf_id', 'target_id', 'data_id', 'new_val', 'note'], 'required'],
            [['new_val', 'note', 'approved_note', 'new_changed'], 'string'],
            [['time_create', 'time_update', 'userkey', 'userkey_status', 'open_status', 'old_val', 'xsourcex'], 'safe']
        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ezf_id' => 'ชื่อฟอร์ม',
            'target_id' => 'ชื่อเป้าหมาย',
            'data_id' => 'Data ID',
            'ezf_field_id' => 'ชื่อคำถาม (ชื่อฟิลด์)',
            'new_val' => 'ค่าใหม่ที่ต้องการแก้ไข',
            'old_val' => 'ค่าเดิม',
            'new_changed' => 'แก้ไขให้เป็น',
            'note' => 'สาเหตุที่ต้องการแก้ไข',
            'status' => 'สถานะ',
            'user_create' => 'ขอแก้โดย',
            'user_update' => 'User Update',
            'time_create' => 'ขอเมื่อ',
            'time_update' => 'Update Time',
            'approved_by' => 'Approved By',
            'approved_note' => 'เหตุผล',
            'userkey' => 'User key',
            'userkey_status' => 'User key (status)',
            'open_status' => 'Status of topic',
            'xsourcex' => 'Site'
        ];
    }
}

backend/controllers/QueryRequestController.php
<?php

namespace backend\controllers;

use backend\models\EzformCoDev;
use backend\models\QueryList;
use backend\models\QueryManager;
use backend\models\QueryReply;
use backend\models\UserProfile;
use backend\modules\ezforms\components\EzActiveForm;
use backend\modules\ezforms\components\EzformQuery;
use backend\modules\ezforms\models\Ezform;
use backend\modules\ezforms\models\EzformDynamic;
use backend\modules\ezforms\models\EzformFields;
use backend\modules\ezforms\models\EzformSqlLog;
use backend\modules\ezforms\models\FileUpload;
use Yii;
use backend\models\QueryRequest;
use backend\models\QueryRequestSearch;
use yii\bootstrap\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\widgets\ActiveField;
use backend\modules\inv\classes\InvFunc;

/**
 * QueryRequestController implements the CRUD actions for QueryRequest model.
 */
class QueryRequestController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all QueryRequest models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new QueryRequestSearch();
        if (Yii::$app->request->get('ezf_id') == 'all') {
            $dataProvider = $searchModel->searchAll(Yii::$app->request->queryParams);

            return $this->render('index_all', [
                        'searchModel' => $searchModel,
                        'dataProvider' => $dataProvider,
            ]);
        } else {
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                        'searchModel' => $searchModel,
                        'dataProvider' => $dataProvider,
            ]);
        }
    }

    public function actionViewByForm($ezf_id) {


        if (!isset($_GET['query_status'])) {
            $_GET['query_status'] = '1';
        }
        if (!isset($_GET['type'])) {
            $_GET['type'] = '1';
        }
        $searchModel = new QueryRequestSearch();
        $dataProvider = $searchModel->searchByForm(Yii::$app->request->queryParams, $ezf_id);

        $ezformCoDev = EzformCoDev::find()->where('ezf_id = :ezf_id', [':ezf_id' => $ezf_id])->all();
        $ezform = Ezform::find()->select('ezf_name, user_create')->where('ezf_id = :ezf_id', [':ezf_id' => $ezf_id])->one();

        $chkOwner = QueryManager::find()->where('ezf_id = :ezf_id', [':ezf_id' => $ezf_id])->andWhere('status = :status', [':status' => '1']);
        //ถ้าไม่มี add auto
        if (!$chkOwner->count()) {

            //insert Owner
            Yii::$app->db->createCommand()->batchInsert('query_manager', ['user_id', 'ezf_id', 'status', 'user_group'], [
                            [$ezform->user_create, $ezf_id, '1', '1'],
                    ])
                    ->execute();

            //insert Co-dev
            $arrCodev = [];
            $i = 0;
            foreach ($ezformCoDev AS $val) {
                $arrCodev[$i][] = $val->user_co;
                $arrCodev[$i][] = $ezf_id;
                $arrCodev[$i][] = '2';
                $arrCodev[$i][] = '1';
                $i++;
            }
            if (count($arrCodev)) {
                //VarDumper::dump($arrCodev, 10, true); exit;
                Yii::$app->db->createCommand()->batchInsert('query_manager', ['user_id', 'ezf_id', 'status', 'user_group'], $arrCodev)
                        ->execute();
            }
        }

        //user from site
        $userDataManager = Yii::$app->db->createCommand('SELECT `user_id` AS id, CONCAT(`firstname`, " ", `lastname`) AS text FROM `user_profile` WHERE sitecode = :sitecode', [':sitecode' => Yii::$app->user->identity->userProfile->sitecode,])->queryAll();
        $userDataManager = ArrayHelper::map($userDataManager, 'id', 'text');

        //VarDumper::dump($userDataManager, 10, true); Yii::$app->end();
        //admin กลาง
        $queryManager = QueryManager::find()->where('ezf_id = :ezf_id', [':ezf_id' => $ezf_id])->all();
        $i = 0;
        $userOwnerNotIn = '';
        $initiUserManager = [];
        $initiUserManagerSite = [];
        $userOwnerNotInSite = '';
        foreach ($queryManager AS $val) {
            if ($val->user_group == 1) {
                // 1= ผู้สร้าง
                // 2 = ผู้ร่วมสร้าง
                if ($val->status == 1 || $val->status == 2) {
                    $user = UserProfile::findOne($val->user_id);
                    $queryManager[$i]->user_id = $user->firstname . ' ' . $user->lastname;
                    unset($userDataManager[$val->oldAttributes['user_id']]); //ไม่เอาคนสองกลุ่มนี้
                }
                // 3 datamanager กลาง
                else if ($val->status == 3) {
                    $initiUserManager[] = $val->user_id;
                }
            } else if ($val->user_group == 2) {
                if ($val->status == 1) {
                    $initiUserManagerSite[] = $val->user_id;
                }
            }
            $i++;
        }

        //
        $userOwner = $ezform->user_create;

        //list user site admin
        $userDataManagerSiteAdmin = Yii::$app->db->createCommand('SELECT
	b.`user_id` AS id,
	CONCAT(b.`firstname`, " ", b.`lastname`) AS text
FROM
	`rbac_auth_assignment` as a
INNER JOIN
	user_profile as b
ON a.user_id = b.user_id
WHERE
	b.sitecode = :sitecode AND
	a.item_name = "adminsite";', [':sitecode' => Yii::$app->user->identity->userProfile->sitecode,])->queryAll();
        $userDataManagerSiteAdmin = ArrayHelper::map($userDataManagerSiteAdmin, 'id', 'text');

        foreach ($userDataManagerSiteAdmin as $key => $val) {
            unset($userDataManager[$key]);
        }

//        \appxq\sdii\utils\VarDumper::dump($ezform);

        return $this->render('index_all', [
                    'dataProvider' => $dataProvider,
                    'ezform' => $ezform,
                    'queryManager' => $queryManager,
                    'userDataManager' => $userDataManager,
                    'userDataManagerSiteAdmin' => $userDataManagerSiteAdmin,
                    'userOwner' => $userOwner,
                    'initiUserManager' => $initiUserManager,
                    'initiUserManagerSite' => $initiUserManagerSite,
        ]);
    }

    public function actionSaveDataManager() {
        if (Yii::$app->getRequest()->isAjax) {
            if (Yii::$app->request->get('action') == 'central') {
                $user_group = 1;
                $status = 3;
            } else if (Yii::$app->request->get('action') == 'site') {
                $user_group = 2;
                $status = 1;
            }

            $ezf_id = Yii::$app->request->post('ezf_id');
            Yii::$app->db->createCommand("DELETE FROM query_manager WHERE ezf_id='$ezf_id' AND status = :status AND user_group = :user_group;", [
                ':user_group' => $user_group,
                ':status' => $status,
            ])->query();
            $user_id = Yii::$app->request->post('val');
            $values = '';
            //$userlist = '';
            foreach ($user_id as $k => $val) {
                $values .= "('$ezf_id', '$val', '$status', '$user_group'), ";
                //$userlist .= ',' . $val;
            }

            $values = substr($values, 0, -2);
            //$userlist = substr($userlist, 1);

            $sql = "INSERT INTO query_manager (`ezf_id`, `user_id`, `status`, `user_group`) VALUES" . $values;
            Yii::$app->db->createCommand($sql)->query();

            //
            Yii::$app->response->format = Response::FORMAT_JSON;
            $result = [
                'status' => 'success',
                'action' => 'create',
                'message' => '<strong><i class="glyphicon glyphicon-ok-sign"></i> Success!</strong> ' . Yii::t('app', ''),
            ];
            return $result;
        }
    }

    public function actionEncodeJsonOldval() {
        VarDumper::dump($_POST, 10, true);
        Yii::$app->end();
        //return json_encode($_POST['SDDynamicModel']);
    }

    /**
     * Displays a single QueryRequest model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        $model = $this->findModel($id);
        $modelQueryLog = QueryRequest::find()->where('ezf_id = :ezf_id', [':ezf_id' => $model->ezf_id])->andWhere('ezf_field_id = :ezf_field_id', [':ezf_field_id' => $model->ezf_field_id])->andWhere('target_id = :target_id', [':target_id' => $model->target_id])->orderBy(['time_create' => SORT_DESC])->all();

        if ($model->status == 1) {
            $model->status = 'Waiting';
        } else if ($model->status == 2) {
            $model->status = 'Resolve with some change';
        } else if ($model->status == 3) {
            $model->status = 'Resolve without any change';
        } else if ($model->status == 4) {
            $model->status = 'Unresolvable';
        } else if ($model->status == 5) {
            $model->status = 'Remark';
        }
        //

        $targetId = $model->target_id;
        if ($model->target_id) {
            //$user = common\models\UserProfile::findOne($model->target);
            //echo $ezf_table_comp; echo'<hr>'; print_r($arr_comp_desc_field_name); exit;
            $comp_name = new \backend\models\Dynamic();
            $ezf_table_comp = \backend\modules\ezforms\components\EzformQuery::checkIsTableComponent($model->ezf_id);
            $arr_desc = explode(',', $ezf_table_comp['field_id_desc']);
            $arr_comp_desc_field_name = [];
            foreach ($arr_desc AS $val) {

backend/views/query-request/_approved.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\QueryRequest */
/* @var $form yii\widgets\ActiveForm */
?>
<style>
    .datepicker{
        z-index: 3000 !important;
    }
</style>
<div class="query-approved-form">

    <?php $form = ActiveForm::begin(['id'=>$model->formName(), 'options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="modal-header">
        <button type="button" class="close closeViewResolution" >&times;</button>
        <h1 class="modal-title" id="itemModalLabel">Query resolution</h1>
    </div>

    <div class="modal-body">

        <?php // echo $form->field($model, 'note')->textarea(['rows' => 6, ])->label('สาเหตุที่ต้องการแก้ไข') ?>

        <?php
//        if($queryManager->user_id){
//            echo Html::button('<i class="fa fa-pencil-square-o"></i> ' . 'Approve', ['class' => 'btn btn-danger btn-md', 'onclick' => '$(\'#query-status\').toggle();']);
//        }
        if($queryManager->user_id) {
            $items = [
                //'1' => 'Waiting',
                '2' => 'Resolve with some change',
                '3' => 'Resolve without any change',
                '4' => 'Unresolvable',
                //'5' => 'Remark',
            ];
            echo '<br><br>'.$form->field($model, 'status')->radioList($items, ['id' => 'query-status'])->label(false);
        ?>
            <div id="QueryRequest-new_changed">
                <?php //echo \yii\bootstrap\Html::button('คัดลอกค่าที่ต้องการแก้ไข', ['onclick'=>'$("#queryrequest-new_changed").val(\''.$model->new_val.'\');', 'class'=>'btn btn-success btn-xs']) ?>
                <?php //$form->field($model, 'new_changed')->textarea(['rows' => 4, ]);
                $options_input['query_tools_render'] = 2;
                $options_input['query_tools_input'] = 9;
                echo \backend\modules\ezforms\components\EzformFunc::getTypeEform($model_gen, $ezf_field, $form, $options_input);
                ?>
            </div>
        <?php
        } ?>

        <?= Html::hiddenInput('ezf_field_type', $ezf_field->ezf_field_type, []);?>
        <?= Html::hiddenInput('ezf_field_name', $ezf_field->ezf_field_name, []);?>
        <?php // echo  $form->field($model, 'user_create')->textInput(['maxlength' => true]) ?>

        <?php // echo $form->field($model, 'user_update')->textInput(['maxlength' => true]) ?>

        <?php // echo $form->field($model, 'time_create')->textInput() ?>

        <?php // echo $form->field($model, 'time_update')->textInput() ?>

        <div id="QueryRequest-approved_note">
            <?= $form->field($model, 'approved_note')->textarea(['rows' => 5, ]) ?>
            <?= $form->field($model, 'note[]')->widget(\kartik\widgets\FileInput::classname(),[
                'pluginOptions' => [
                    'allowedFileExtensions'=>['pdf','png','jpg','jpeg'],
                    'showRemove' => false,
                    'showUpload' => false,
                ],
                'options' => ['multiple' => true]
            ])->label('File Upload'); ?>
        </div>


    </div>

    <div class="modal-footer">
        <div class="form-group">
            <?= Html::submitButton('Submit', ['id' => 'btn-query', 'class' => 'btn btn-success btn-lg','data-url' => yii\helpers\Url::to(['/query-request/approved-query'])]) ?>
            <?= Html::button('Cancel', ['class' => 'btn btn-danger btn-lg closeViewResolution']); ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
$this->registerJs('$(function() { $("div[id=\'QueryRequest-new_changed\']").find(\'input,select,textarea\').prop(\'disabled\', true); });');
$this->registerJs("

$('form#{$model->formName()}').on('submit', function(e) {
    e.preventDefault();
    var \$form = $(this);
    var url = \$form.attr('action');
        var data = \$form.serialize();
         $.ajax({
            url:url,
            method:'POST',
            dataType:'json',
            data:data,
            success:function(data){
                " . \appxq\sdii\helpers\SDNoty::show('data.message', 'data.status') . ";
                $('#modal-query-resolution').modal('hide');
                $('#saveValue').val('1');
            },
            error:function(error){
                " . \appxq\sdii\helpers\SDNoty::show("'" . \appxq\sdii\helpers\SDHtml::getMsgError() . "'", '"error"') . ";
                $('#modal-query-resolution').modal('hide');
                $('#saveValue').val('1');
            }
        });
        return false;
});

$('.closeViewResolution').on('click',function(){
    $('#modal-query-resolution').modal('hide');
});

//$(\"#query-status\").on('change', function() {
//    var status = $('input[name=\"QueryRequest[status]\"]:checked').val();
//    if(status==1){
//        $('#QueryRequest-new_changed').hide();
//        $('#QueryRequest-approved_note').hide();
//        //$('#btn-query').text('Query');
//    }
//    else if(status==2){
//        $('#QueryRequest-new_changed').fadeIn();
//        //$('#QueryRequest-approved_note').fadeIn();
//        //$('#btn-query').text('Query');
//    }
//    else if(status==3){
//        $('#QueryRequest-new_changed').hide();
//        //$('#QueryRequest-approved_note').fadeIn();
//        //$('#btn-query').text('Query');
//    }
//    else if(status >=4){
//        $('#QueryRequest-new_changed').hide();
//        //$('#QueryRequest-approved_note').fadeIn();
//        //$('#btn-query').text('Respond');
//    }
//});
//$(function() {
//    $('#QueryRequest-new_changed').hide();
// });
");
?>

backend/views/query-request/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
//use common\lib\damasac\assets\date\DMSDateAsset;
//use kartik\select2\Select2;
//use kartik\select2\Select2Asset;
/* @var $this yii\web\View */
/* @var $model backend\models\QueryRequest */
/* @var $form yii\widgets\ActiveForm */
//DMSDateAsset::register($this);
//Select2Asset::register($this);
?>
<style>
    .datepicker{
        z-index: 3000 !important;
    }
</style>

<div class="query-request-form">

    <?php $form = ActiveForm::begin(['id'=>$model->formName(), 'action' => ['create'], 'options' => ['enctype' => 'multipart/form-data']]); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1 class="modal-title" id="itemModalLabel">Query change request</h1>
    </div>

    <?php
    ?>
    <div class="modal-body">
    <?php //Html::textInput('queryrequest-id', '', ['hidden'=>true]); ?>
    <?php echo $form->field($model, 'ezf_id')->textInput(['maxlength' => true,])->hiddenInput(['value' => Yii::$app->request->get('ezf_id')])->label(false); ?>

    <?php echo $form->field($model, 'target_id')->textInput(['maxlength' => true,])->hiddenInput(['value' => $modelValue->target_id])->label(false); ?>

    <?php echo $form->field($model, 'data_id')->textInput(['maxlength' => true,])->hiddenInput(['value' => Yii::$app->request->get('data_id')])->label(false); ?>
    <?php echo $form->field($model, 'xsourcex')->textInput(['maxlength' => true,])->hiddenInput(['value' =>Yii::$app->user->identity->userProfile->sitecode])->label(false); ?>

    <?php echo Html::hiddenInput('ezf_field_type', $ezf_field->ezf_field_type, []);?>
    <?php echo Html::hiddenInput('ezf_field_name', $ezf_field->ezf_field_name, []);?>

    <?php // echo $form->field($model, 'ezf_field_id')->dropDownList($ezf_field, ['prompt'=>'Select Field...',])->label('เลือกข้อคำถามที่ต้องการแก้ไข') ?>

    <?php $model->old_val = json_encode($modeQuery->attributes);  echo $form->field($model, 'old_val')->textarea(['style'=>"display:none;"])->label(false);?>

<!--
    <div id="div-list-ezf-field" style="display:<?php // echo !$model->isNewRecord ? '' : 'none'; ?>;">
        <div style="padding: 10px;" class="alert-success" id="list-ezf-field"></div><br>
    </div>

    <div id="queryrequest-label-note" style="display: <?php // echo !$model->isNewRecord ? '' : 'none'; ?>;">
    <?php //echo $form->field($model, 'new_val')->textarea(['rows' => 6, 'disabled' => true])->hiddenInput()->label(false); ?>

    <?//= $form->field($model, 'note')->textarea(['rows' => 6, ])->label('สาเหตุที่ต้องการแก้ไข') ?>
    </div>
-->
    <?php echo Html::label('ค่าใหม่ที่ต้องการแก้ไข') ?>
    <?php
    //\yii\helpers\VarDumper::dump($options_input);
    if($ezf_field->ezf_field_type != 14 && $ezf_field->ezf_field_type != 13)
    echo backend\modules\ezforms\components\EzformFunc::getTypeEform($modeQuery, $ezf_field, $form, $options_input);
    echo $form->field($model, 'ezf_field_id')->textInput()->hiddenInput(['value' => Yii::$app->request->get('ezf_field_id')])->label(false);
    //echo \backend\modules\ezforms\components\EzformWidget::activeDateInputSave($form, $modeQuery, 'new_val', $ezf_field, null);
     ?>

    <?php echo $form->field($model, 'note')->textarea(['rows' => 6, ])->label('สาเหตุที่ต้องการแก้ไข') ?>

    <?php
    if($queryManager->user_id || Yii::$app->user->can('adminsite')) {
        echo Html::label('ต้องการ Query ถึง...');
        echo \kartik\widgets\Select2::widget([
            'id' => 'queryUserTo',
            'name' => 'queryUserTo',
            'value' => [$modelValue->user_create], // initial value
            'data' => $userTo,
            'options' => ['placeholder' => 'Select user ...', 'multiple' => false],
            'pluginOptions' => [
                'allowClear' => true
                //'maximumInputLength' => 10
            ],
        ]);
    }
    ?>

    <?php // echo $form->field($model, 'user_create')->textInput(['maxlength' => true]) ?>

    <?php // echo $form->field($model, 'user_update')->textInput(['maxlength' => true]) ?>

    <?php // echo $form->field($model, 'time_create')->textInput() ?>

    <?php // echo $form->field($model, 'time_update')->textInput() ?>

    <?php // echo $form->field($model, 'approved_by')->textInput(['maxlength' => true, 'value' => $modelValue->user_create]) ?>

    <?php echo $form->field($model, 'userkey')->textInput(['maxlength' => true,])->hiddenInput(['value' => $modelValue->user_create])->label(false); ?>
    </div>

    <div class="modal-footer">
        <div class="form-group">
            <?php echo Html::submitButton($model->isNewRecord ? 'Edit' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success btn-lg' : 'btn btn-primary btn-lg',]) ?>
        </div>
    </div>

    <?php ActiveForm::end();
    $this->registerJs("
    function getDataFromTable(ezf_field_id){

        var data_id = '".$model->data_id."';
        var url = '".\yii\helpers\Url::to(['/query-request/find-data-model',])."';
        $.ajax({
            type: 'POST',
            url: url,
            data: {data_id: data_id, ezf_field_id : ezf_field_id},
            dataType: 'json',
            success: function(data) {
                if(data.note || data.new_val){
                    //update
                    $(\"#queryrequest-note\").val(data.note);
                    //$(\"#queryrequest-new_val\").val(data.new_val);
                    $(\"[name='queryrequest-id']\").val(data.id);

                    url = '".\yii\helpers\Url::to(['/query-request/select-data-field',])."';
                    //var htmlx ='';
                    var query_id = data.id;
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {query_id: query_id, ezf_field_id : ezf_field_id},
                        //dataType: 'json',
                        success: function(data) {
                            // you can use data.blah, or if working with multiple rows
                            // of data, then you can use $.each()
                            //htmlx = '<h3>ข้อมูลค่าเดิม</h3>';
                            //htmlx += ''+data.text;
                            //htmlx += '<hr>';
                            $(\"#list-ezf-field\").html(data);
                            $(\"#div-list-ezf-field\").fadeIn();
                            $(\"#queryrequest-label-note\").fadeIn();
                            $(\".field-queryrequest-old_val\").html('');
                        }
                    });
                }else{
                    //create
                    url = '".\yii\helpers\Url::to(['/query-request/select-data-field',])."';
                    //var htmlx ='';
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {data_id: data_id, ezf_field_id : ezf_field_id},
                        //dataType: 'json',
                        success: function(data) {
                            // you can use data.blah, or if working with multiple rows
                            // of data, then you can use $.each()

                            //htmlx = '<h3>ข้อมูลค่าเดิม</h3>';
                            //htmlx += ''+data.text;
                            //htmlx += '<hr>';
                            //htmlx = data;
                            $(\"#list-ezf-field\").html(data);

                            if(data.text=='ไม่มีค่าข้อมูล'){
                                data.text=null;
                            }
                            $(\"#queryrequest-old_val\").val($(\"#queryrequest-new_val\").val());

                            $(\"[name='queryrequest-id']\").val(null);
                            $(\"#queryrequest-note\").val('');
                            //$(\"#queryrequest-new_val\").val('');
                            $(\"#div-list-ezf-field\").fadeIn();
                            $(\"#queryrequest-label-note\").fadeIn();
                        }
                    });
                }
            }
        });

    }
    $('#".$model->formName()."').on('change', '#queryrequest-ezf_field_id', function(){
        var ezf_field_id = $(this).val();
        getDataFromTable(ezf_field_id);
    });


/*
$(function() {
    var datastring = $(\"#QueryRequest\").serialize();
    var url = '".\yii\helpers\Url::to(['/query-request/encode-json-oldval',])."';
        $.ajax({
            type: \"POST\",
            url: url,
            data: datastring,
            success: function(data) {
                 //$(\"#queryrequest-old_val\").val(data);
            }
        });
});
*/

$('form#{$model->formName()}').on('beforeSubmit', function(e) {
               
     var \$form = $(this);
     $.post(
        \$form.attr('action'),
        \$form.serialize()
    ).done(function(result) {
        " . \common\lib\sdii\components\helpers\SDNoty::show('result.message', 'result.status') . ";
        $('#modal-query-request').modal('hide');
    }).fail(function() {
        " . appxq\sdii\helpers\SDNoty::show("'" . appxq\sdii\helpers\SDHtml::getMsgError() . "'", '"error"') . "
        $('#modal-query-request').modal('hide');
    });
    return false;
});

    ");

//    if(!$model->isNewRecord){
//        $this->registerJs("
//        getDataFromTable('".$model->ezf_field_id."');
//        ");
//    }

    ?>

</div>

backend/views/query-request/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\QueryRequest */

$this->title = 'Create Query Request';
$this->params['breadcrumbs'][] = ['label' => 'Query Requests', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="query-request-create">

    <?= $this->render('_form', [
        'model' => $model,
        'modelValue' => $modelValue,
        'modeQuery' => $modeQuery,
        'ezf_field' => $ezf_field,
        'options_input' => $options_input,
        'queryManager' => $queryManager,
        'userTo' =>$userTo
    ]) ?>

</div>